import type { Media } from './types';

export const mediaData: Media[] = [
  {
    id: 1,
    title: 'Stellar Odyssey',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    type: 'movie',
    genre: 'Sci-Fi',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=Stellar+Odyssey',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['trending'],
  },
  {
    id: 2,
    title: 'The Crown of Kings',
    description: 'Nine noble families fight for control over the mythical lands of Westeros, while a forgotten race returns after being dormant for thousands of years.',
    type: 'show',
    genre: 'Fantasy',
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=The+Crown+of+Kings',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['trending'],
  },
  {
    id: 3,
    title: 'Echoes of the Past',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    type: 'movie',
    genre: 'Thriller',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=Echoes+of+the+Past',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['new-release'],
  },
  {
    id: 4,
    title: 'The Chemist',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    type: 'show',
    genre: 'Drama',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=The+Chemist',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['trending'],
  },
  {
    id: 5,
    title: 'Cybernetic Dawn',
    description: 'In a dystopian future, a cyborg is sent from the future on a deadly mission.',
    type: 'movie',
    genre: 'Action',
    cast: ['Keanu Reeves', 'Carrie-Anne Moss', 'Laurence Fishburne'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=Cybernetic+Dawn',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['new-release'],
  },
  {
    id: 6,
    title: 'Mind Hunters',
    description: 'Two FBI agents, with the help of a brilliant psychologist, track down serial killers.',
    type: 'show',
    genre: 'Crime',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=Mind+Hunters',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: [],
  },
  {
    id: 7,
    title: 'The Last Stand',
    description: 'A post-apocalyptic saga of a survivor who fights his way across a desolate landscape.',
    type: 'movie',
    genre: 'Apocalyptic',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=The+Last+Stand',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: ['new-release', 'trending'],
  },
  {
    id: 8,
    title: 'Parallel Worlds',
    description: 'The adventures of an eccentric and alcoholic scientist and his naive grandson.',
    type: 'show',
    genre: 'Animation',
    cast: ['Justin Roiland', 'Chris Parnell', 'Spencer Grammer'],
    coverImage: 'https://placehold.co/800x1200/141414/E50914?text=Parallel+Worlds',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    tags: [],
  },
];
